name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0" # Replace with your desired .NET version

      # Step 3: Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # Step 4: Build the Application
      - name: Build Application
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run Tests
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "Cse415FinalProjectWebb" # Replace with your Azure app name
          slot-name: "production"         # Replace with your deployment slot (e.g., production)
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
